name: Release

permissions:
  contents: write

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    name: Build and Publish ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            args: ''
          - name: MacOS(arm)
            os: macOS-latest
            args: '--target aarch64-apple-darwin'
          - name: MacOS(intel)
            os: macOS-latest
            args: '--target x86_64-apple-darwin'
          - name: Ubuntu
            os: ubuntu-latest
            args: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.args }}
          releaseDraft: true
          prerelease: false
          releaseName: 'v__VERSION__'
