name: Release

on:
  workflow_dispatch: # 允许手动触发

jobs:
  publish-tauri:
    permissions:
      contents: write
    name: Build and Publish ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
            args: ''
          - name: MacOS(arm)
            os: macOS-latest
            args: '--target aarch64-apple-darwin'
          - name: MacOS(intel)
            os: macOS-latest
            args: '--target x86_64-apple-darwin'
          - name: Ubuntu
            os: ubuntu-latest
            args: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Setup Rust(Macos Arm)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && contains(matrix.name, 'arm') && 'aarch64-apple-darwin' || '' }}

      - name: Setup Rust(Macos Intel)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && contains(matrix.name, 'intel') && 'x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build And Publish
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          includeUpdaterJson: true
          prerelease: false
          uploadPlainBinary: true
          args: ${{ matrix.args }}